### ISSUE TITLE
Gravity Force Lab: Basics Master Checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/gravity-force-lab-basics#16]
## Design
- [x] **Sim folder and design doc created** (Date: 08/18/16) 
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Sim suggestions doc reviewed**
- [x] **Learning goals and standards identified** (Date: 07/07/16)
- [x] **Design concept complete**  (Date: 08/18/16)
- [x] **Wireframes complete** (Date: 08/18/16) 
- [x] **Mockups complete** (Date: 2/10/17) 
  - [x] Mockups checked for colorblind and greyscale
- [x] **Features for PhET-iO discussion** 
- [x] **Interviews complete** (Date: 04/16/18) 
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 04/11/18) 
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Main screenshot (read [this](https://github.com/phetsims/QA/blob/master/doc/qa-book.md#screenshots))
  - [x] Auxilary screenshots (up to 3 additional)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  - [x] Add an activity
  - [x] Sim primer draft  -- see #67 
  - [x] Verify credits
  - [x] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive
  - [x] LoL [metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use)
- [x] **Post-publication items** 
  - [x] Add the simulation to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] Add to [Gooru](http://gooru.org/PhET/content/resources) (signed in as phethelp)
  - [x] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [x] Sim primer (create issue, publish ideally within 1 month of live sim) -- see #67 
  - [x] Hold postmortem if applicable (Date: 11/7/2019) 

## Implementation
- [x] **Repository created** (Date: 08/23/2016)
  - [x] simula-rasa used to create project skeleton
  - [x] README.md created using `grunt unpublished-readme`
  - [x] Collaborators added (such as QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to chipper/data/ files
- [x] **Development started** (Date: 12/14/2016)
- [x] **Sim is "feature complete"** (Date: 6/2/2019) 
- [x] **Code review completed** (Date: 7/1/2019) 
- [x] **Published** (Date: 10/25/2019) 
  - [x] README.md updated using `grunt published-readme` (in master and release branch)
 
## QA
- [x] **Dev testing started** (Date: 01/10/18) 
- [x] **Dev testing completed** (Date: 02/20/18) 
- [x] **A11y Dev testing completed** (Date: 6/4/19) 
- [x] **First RC published** (Date: 9/17/19)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 10/25/19)

**Comment by zepumph** [comment]
I got an email my production build succeeded, over to you @arouinfar to take us home.

**Comment by arouinfar** [comment]
@ariel-phet the remaining items are yours.

**Comment by zepumph** [comment]
Pinging @ariel-phet because I think this one will be quick.
