### ISSUE TITLE
Ready 1.0.0-rc.2

### ISSUE THREAD

**Issue by zepumph** [phetsims/gravity-force-lab-basics#179]
https://github.com/phetsims/QA/issues/429 went very well! We are almost ready for the next rc. During this process, I applied a patch from https://github.com/phetsims/inverse-square-law-common/issues/79 which then caused a problem for @jonathanolson  doing some MRs. As a result I'm going to add MR patches myself for this release.

TODO:
- [x]  Make sure that https://github.com/phetsims/inverse-square-law-common/issues/79 is still good
- [x] Cherry pick in the added period in https://github.com/phetsims/gravity-force-lab-basics/issues/177 (https://github.com/phetsims/gravity-force-lab/commit/a34682a500a903cd41440e3b64bf70813bf03324)
- [x] Add MR patches:
  * cherry-pick https://github.com/phetsims/scenery/commit/df959930510e40591b027c4efeded70018a974e3
  * make sure it has the https://github.com/phetsims/joist/commit/85cfbfa973322f6f4c954f12202161c30ebfaff8 patch also
- [x]  https://github.com/phetsims/gravity-force-lab-basics/issues/181
- [x] https://github.com/phetsims/scenery/issues/1001
- [x] https://github.com/phetsims/gravity-force-lab-basics/issues/183 (still need to do the GFL)
- [x] https://github.com/phetsims/gravity-force-lab-basics/issues/182

**Comment by zepumph** [comment]
Don't forget about https://github.com/phetsims/gravity-force-lab-basics/issues/183

**Comment by zepumph** [comment]
Done. https://github.com/phetsims/QA/issues/438

**Comment by zepumph** [comment]
Note this was pretty difficult. Especially for https://github.com/phetsims/gravity-force-lab-basics/issues/181 which had many sun commits, most were after a batch change from `var` to `const` in require statements, and so it took a while to realized I needed to add those commits in as well to avoid cherry-pick issues.
