### ISSUE TITLE
Progress on description implementaion for this sim

### ISSUE THREAD

**Issue by terracoda** [phetsims/gravity-force-lab-basics#84]
On October 25, 2019 this sim was published with Alternative Input, Sonification, Interactive Description, and Interactive Description on Mobile 

This sim is being outfitted for the following accessibility features:
- [x] Keyboard Navigation - Alternative Input
- [x] Simple Description - Minimal Static State Descriptions
- [x] Full Description - All State & Responsive Descriptions
- [x] Sonification & Mute Sound toggle button (https://github.com/phetsims/gravity-force-lab-basics/issues/166)
- [x] Mobile Accessibility (covered in the 3 RC's)
- [x] RC 4 spot check completed - October 25, 2019

Implementation of descriptions for Gravity Force Lab Basics is quite far along due to initial work on Gravity Force Lab (regular).

Some changes to labels (m1 to be mass 1 and m2 to be mass 2) and content (simplification of some language) is required for this sim.

This issue helps tracks the big picture progress for description implementation.

**Link to [GFLB A11y Design Main](https://docs.google.com/document/d/1HdDG9ds2MdbCb21l9qk3cI8yBQxK6-wBWNXC4Tloji8/edit#heading=h.gnyv76vd5fvr)** 

**Implementation of PDOM**
**Common Static Descriptions & Items**
- [x] Focus order correct
- [x] H1 for sim title
- [x] Sim Regions & H2 Headings (Play Area, Control Area, Sim Resources)
- [x] Static part of screen summary (update verified https://github.com/phetsims/gravity-force-lab-basics/issues/133)
- [x] Keyboard Shortcuts interaction hint is in scene/screen summary
- [x] Initial sim-specific interaction hint in 

**Static Descriptions (Play Area)**
- [x] Sim-specific H3s for sim objects
- [x] Labels for all interactive items
- [x] Help text for interactive items

**Static Descriptions (Control Area)** 
- [x] Sim-specific H3s for Control Area (none for this sim)
- [x] Labels for checkboxes
- [x] Help text for checkboxes
- [x] Reset All button

**Sim Resources (Sim Resources)**
- [x] Keyboard Shortcuts button added
- [x] Related Interaction hint is in scene/screen summary 

**Dynamic Descriptions**
- [x] Dynamic descriptions for the State of the Sim
  - [x] Simplification to wording complete
  - [x] Constant Size (comparative density description)
    - [x] Constant Size descriptions implemented
- [x] Dynamic descriptions for Mass Spheres
  - [x] Simplification to wording complete

**Interaction Alerts**
**[Simple Interaction Alerts for UI Options](https://docs.google.com/document/d/1HdDG9ds2MdbCb21l9qk3cI8yBQxK6-wBWNXC4Tloji8/edit#heading=h.mp3sseh3ze8h)**
  - [x] Alerts for checking/unchecking checkboxes (updated)
  - [x] Reset All alert, verified

**[Complex Interaction Alerts](https://docs.google.com/document/d/1HdDG9ds2MdbCb21l9qk3cI8yBQxK6-wBWNXC4Tloji8/edit#heading=h.mgmn7olsqd39)**
**Sphere Position slider description/alerts (aria-valuetext) - describes changes to distance between spheres**
  - [x] Position information on focus
  - [x] Position changes: decreasing distance
  - [x] Position changes: increasing distance
  - [x] Edge cases for position/distance - changed to Right edge, Left edge, and Last stop (touching)
  - [x] Described distance: qualitative distance added when Distance checkbox is unchecked 
    - [x] New value ranges for described distance implemented see https://github.com/phetsims/gravity-force-lab-basics/issues/88#issuecomment-463609792
  - Based on interview feedback rethinking position/distance, see #107
    - [x] Iterations to position: (Track end left/right, Last stop left/right, Left/Right side of track) 
 
**Sphere position force alerts (ARIA live region)**
  - [x] Force information on position focus (position slider focus alert)
    - [x] @terracoda to verify with consultants that we need a force focus alert - removed focus alerts
  - [x] Force information as position changes (position/distance force alerts)
  - [x] Simplification to wording in alerts complete 
 
**Mass number pickers descriptions/alerts (aria-valuetext) - describes changes to mass or density of spheres**
  - [x] Mass value changes in aria-valuetext
  - [x] Mass changes: increasing mass of sphere 
  - [x] Mass changes: decreasing mass of sphere

**Mass number pickers force alerts (ARIA live region)**
  - [x] Force information on focus of mass (mass focus alert)
    - [x] @terracoda to verify with consultants that we need a force focus alert - removed focus alerts  
  - [x] Force information as mass changes (mass force alerts)
  - [x] Edge case 1 (position of same sphere changes as mass increases)
  - [x] Edge case 2 (position of other sphere changes as mass increases)
  - [x] Simplification to wording complete
  
**Mobile A11y**
- [x]  #176 - issue with checkboxes found during RC
- [x] #119 - coming along nicely, but haven't yet closed issue
- [x] Discuss issue about about dynamic `aria-valuetext` with MK
   -  [x] Left/Right side of track - design solution - provide on start and special cases (see https://github.com/phetsims/gravity-force-lab-basics/issues/124#issuecomment-493950652)
   -  [X] Comparative Mass and Density descriptions - design solution moved comparative description to PDOM

**Other Features & Items (Keyboard Shortcuts, Sim Resources)**
- [x] Visual Keyboard Shortcuts Dialog
  - [X] #118 Remove Small steps for Mass & add Basic Action for checkboxes
- [x] Accessible content for Keyboard Shortcuts dialog added
- [x] Keyboard Shortcuts button added to Sim Resources

**Check Credits**
- [x] Verify A11y team has been added
  - [x] - Team: add Emily B. Moore, Taliesin Smith, Brianna Tomlinson (https://github.com/phetsims/gravity-force-lab-basics/issues/154#issuecomment-503473793)
  - [x] - Software Development: add John Blanco, Michael Kauzmann
  - [x] - Sound Design: Ashton Morris after Graphics Arts

**Once Evaluation begins**
- [x] Ensure interviews are recorded to this sim's interview spreadsheet

**During QA or just after publication**
- [x] KW mentioned that the weird number bug was reported during QA in the QA issue. @terracoda to check with @zepumph on this. 
- [x] Clean and polish up A11y design doc
- [x] List out main design challenges (in progress, get opinions from devs & designers)
- [x] List out lessons learned from this sim, e.g. found focus issues for iOS (in progress, get opinions from devs & designers)
- [x] Make a description design github issue template (see https://github.com/phetsims/a11y-research/blob/master/issue-templates/description-design-template.md)

**List of changes to Checklist (by date)**
Tue. Apr 30, 2019 - updated Credits and added 2 new sections for post design work, updated a bit more
Mon. Apr 1, 2019 - checked constant size description, split issue 107 into to items
Wed. Mar 6, 2019 - Added new item for iteration on position/distance
Tue. Feb 19, 2019 - checked off more items, added issues to specific things
Mon. Jan 28, 2019 - checked off more items
Mon. Jan 14, 2019 - removed duplication, re-arranged list slightly, added some more items

**Comment by terracoda** [comment]
@zepumph, I am still working on this check list and will be making sure it is up to date for our meeting next week.

**Comment by zepumph** [comment]
Sounds good. Unassigning for now, let's talk more about it tonight.

**Comment by terracoda** [comment]
**Final list of things to do**
- [ ] #114 - @terracoda to review before Monday May 6th
- [ ] #116 - assigned to @zepumph , med priority
- [ ] #119 - mobile a11y, coming along nicely
- [ ] #120 - min force bug? assigned to @zepumph 
- [ ] #122 - consultant interviews scheduled for March 7th and maybe 10th (high priority)
- [ ] #124 - redesign of position sliders, @terracoda to make clear before Monday for @zepumph (top priority)
- [ ] #125 - redesign of mass number spinners - assigned to @zepumph (top prioroty)

**Comment by zepumph** [comment]
This sim has been published, anything else here @terracoda?

**Comment by terracoda** [comment]
On October 25, 2019 this sim was published with Alternative Input, Sonification, Interactive Description, and Interactive Description on Mobile.

@zepumph, I think that's a wrap, closing this issue!
